### ISSUE TITLE
Problems with removing nodes/pieces

### ISSUE THREAD

**Issue by Choccy-vr** [CMDRSpirit/RollercoasterDesigner#5]
Hello I just got this package and it is great. Altough when removing a piece/node it glitches out throws a bunch of errors and doesn't let you move around the editor until you delete the coaster.

**Comment by CMDRSpirit** [comment]
Hi, thanks for reporting. Can you post the error log?

**Comment by Choccy-vr** [comment]
This is the error I get `MissingReferenceException: The object of type 'Rollercoaster.TrackSection' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.Object+MarshalledUnityObject.TryThrowEditorNullExceptionObject (UnityEngine.Object unityObj, System.String parameterName) (at <386c10ac68fc4fc89720e76e5a26273c>:0)
UnityEngine.Bindings.ThrowHelper.ThrowNullReferenceException (System.Object obj) (at <386c10ac68fc4fc89720e76e5a26273c>:0)
UnityEngine.Component.GetComponentFastPath (System.Type type, System.IntPtr oneFurtherThanResultValue) (at <386c10ac68fc4fc89720e76e5a26273c>:0)
UnityEngine.Component.GetComponent[T] () (at <386c10ac68fc4fc89720e76e5a26273c>:0)
Rollercoaster.TrainAudioManager.Update () (at Assets/RollercoasterDesigner-main/Scripts/Audio/TrainAudioManager.cs:143)
`. Although I was removing the pieces wrong at the time it still sometimes does still do that even when you remove it correctly.

**Comment by CMDRSpirit** [comment]
I see. I can't really find out why it only happens sometimes, but I also had the same problem. I think validating the elements of the `TrackSections` variable in `CoasterTrack.cs` can fix the issue temporarily.

**Comment by Choccy-vr** [comment]
Yeah I found the issue when deleting the section through the ui it works fine thanks
